### ISSUE TITLE
What versions of python/java/c++ etc etc  for latest spams?

### ISSUE THREAD

**Issue by HollyRafiqueKCL** [samuelstjean/spams-python#21]
Hi

I am trying to run someone else's code and it requires spams. I have installed my entire environment from scratch (don't normally use this laptop for dev) but the latest versions of pretty much everything seem to be conflicting when I install your version of spams.
I have been able to install every other python package so I think there must be a version of something that won't work.

When I run `pip3 install spams-bin` I get the following error:
```

Building wheels for collected packages: spams-bin
  Building wheel for spams-bin (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for spams-bin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\spams
      copying spams\spams.py -> build\lib.win-amd64-cpython-310\spams
      copying spams\__init__.py -> build\lib.win-amd64-cpython-310\spams
      creating build\lib.win-amd64-cpython-310\spams_wrap
      copying spams_wrap\spams_wrap.py -> build\lib.win-amd64-cpython-310\spams_wrap
      copying spams_wrap\__init__.py -> build\lib.win-amd64-cpython-310\spams_wrap
      running build_ext
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      building 'spams_wrap._spams_wrap' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\spams_wrap
      C:\Users\hooll\AppData\Local\Temp\pip-build-env-shhhbzq2\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:528: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
        warnings.warn(
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ispams_wrap -Ispams_wrap\linalg -Ispams_wrap\prox -Ispams_wrap\decomp -Ispams_wrap\dictLearn -IC:\Users\hooll\AppData\Local\Temp\pip-build-env-shhhbzq2\overlay\Lib\site-packages\numpy\core\include -IC:\Users\hooll\AppData\Local\Programs\Python\Python310\include -IC:\Users\hooll\AppData\Local\Programs\Python\Python310\include -IC:/Miniconda/envs/openblas/Library/include -IC:/Miniconda/envs/openblas/Library/include/openblas -IC:\Users\hooll\AppData\Local\Programs\Python\Python310\include -IC:\Users\hooll\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpspams_wrap/spams_wrap-windows.cpp /Fobuild\temp.win-amd64-cpython-310\Release\spams_wrap/spams_wrap-windows.obj -DNDEBUG -DUSE_BLAS_LIB -fPIC -m64 -openmp
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      cl : Command line warning D9002 : ignoring unknown option '-m64'
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\lib /LIBPATH:C:\ /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:/Miniconda/envs/openblas/Library/lib /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310 /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 openblas.lib openblas.lib /EXPORT:PyInit__spams_wrap build\temp.win-amd64-cpython-310\Release\spams_wrap/spams_wrap-windows.obj /OUT:build\lib.win-amd64-cpython-310\spams_wrap\_spams_wrap.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\spams_wrap\_spams_wrap.cp310-win_amd64.lib
      LINK : fatal error LNK1181: cannot open input file 'openblas.lib'
      error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\lib /LIBPATH:C:\ /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:/Miniconda/envs/openblas/Library/lib /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310 /LIBPATH:C:\Users\hooll\AppData\Local\Programs\Python\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 openblas.lib openblas.lib /EXPORT:PyInit__spams_wrap build\temp.win-amd64-cpython-310\Release\spams_wrap/spams_wrap-windows.obj /OUT:build\lib.win-amd64-cpython-310\spams_wrap\_spams_wrap.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\spams_wrap\_spams_wrap.cp310-win_amd64.lib" failed with exit status 1181 
      [end of output]

```
I have tried to clone the repo and run `python setup.py install `in the spams-python directory but I get this error:
```
Traceback (most recent call last):
  File "C:\Users\<path>\spams-python\setup.py", line 94, in <module>
    incs, libs, libdirs, cc_flags, link_flags = get_config()
  File "C:\Users\<path>\spams-python\setup.py", line 26, in get_config
    for _ in np.__config__.blas_opt_info.get('extra_compile_args', []):
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'
```

current env:
OS:         Windows 11
Python:   3.10.4
Java:        JDK 18
Visual Studio Build Tools 2022 - 17.1.6:
C++ compiler:       MSVC  14.31.31103

All python packages are the most recent ones

Or am I missing something else? (BLAS??)

**Comment by HollyRafiqueKCL** [comment]
Have just installed Anaconda and managed to install spams-bin on there using pip3 - very strange but at least I have a copy now

**Comment by samuelstjean** [comment]
I think that newer version of numpy changed some things internally we used for detection, so that might be why. And I probably didn't have any build for py3.10 yet, so installing anaconda might just have grabbed an older version because of that. We're actually trying to centralize all those fixes around here now https://github.com/getspams/spams-python, still working toward making it work so that's why I am keeping this one here for now.
